### ISSUE TITLE
Metadaten/SEO

### ISSUE THREAD

**Issue by MiragonMx** [MiragonMx/aurealm_web#76]
- [x] register with google for indexing
- [x] register w/ bing/ecosia/startpage??
- [x] configure robots.txt
- [x] add keywords to metadata
- [x] add site description meta tags (s. [link](https://developers.google.com/search/docs/appearance/snippet?hl=de)) (translation??)
- [x] Sitemap: don't use date for 'startdate' in metadata, otherwise sitemaps will assume, that 'fictional' date, e.g. 1237-10-23 is the 'last-modified' date and will not crawl
- [x]  Sitemap still not crawled, but might get there, check in some days in search console

**Comment by MiragonMx** [comment]
`noindex` meta-tag is more appropriate for the currently excluded pages, as a `robots.txt` exclusion would still make them crawlable from linking pages, thus actually not as relevant as I thought, other metatags and keywords more important for SEO!

**Comment by MiragonMx** [comment]
register w/ bing/yahoo: [link](https://seo-summary.de/homepage-bei-suchmaschinen-anmelden/)

**Comment by MiragonMx** [comment]
- [ ] add site description meta tags (s. [link](https://developers.google.com/search/docs/appearance/snippet?hl=de)) (translation??)

**Comment by MiragonMx** [comment]
@Murthyan97 ping, just for tracking ideas/changes
- added more tasks, especially the change from `date` to `startdate` will then need your attention, so new sites use this correctly
- will tell you, once this is relevant
- GSC doesn't list the site yet, might also be crawled from Insta, or maybe the dashboard is not 100% in sync with google's backend, but nice, that we get it already

**Comment by Murthyan97** [comment]
> register w/ bing/yahoo: [link](https://seo-summary.de/homepage-bei-suchmaschinen-anmelden/)

done

**Comment by Murthyan97** [comment]
Do you need a list of keywords for SEO? Could be senseful to add further keywords (like free rulebook, etc.) in later stages

**Comment by MiragonMx** [comment]
> Do you need a list of keywords for SEO? Could be senseful to add further keywords (like free rulebook, etc.) in later stages

Would make sense I think :)

**Comment by MiragonMx** [comment]
PR #167  should address the descriptions (@Murthyan97 you can change them in hugo.toml as you like) and possibly also the sitemap problem. still not sure about how to handle keywords

**Comment by MiragonMx** [comment]
![image](https://github.com/MiragonMx/aurealm_web/assets/80544476/2d4468d2-9b72-4004-94ed-d838f7af4f1e)
![image](https://github.com/MiragonMx/aurealm_web/assets/80544476/f73f1b1f-d975-470c-a314-d0d4483a26f0)
Also, at least the 'automatic' SEO assessment from Lighthouse likes what I did

**Comment by MiragonMx** [comment]
I looked into the keyword question some more... It seems like this sort of meta tag is not used by most common search engines anymore (except for _maybe_ a russian one) but only sometimes by site-internal searches. If that would become a question, there's other ways in hugo and I would opt for hugo's tag system if we would want to use something like that. [reference](https://ahrefs.com/blog/de/meta-keywords/)

Thus, I think SEO is pretty much done! 
We already only use quite little CSS/js so the site should be quite crawler/bot friendly and the other common tips are quite well done by us i think (see, e.g., [here](https://www.robotstxt.org/faq/bestlisting.html))

@Murthyan97 please confirm this when you have some time to look/think it over! If this seems fine with you, I would then close this issue as completed :)
